services:
  awesome_api:
    build: .
    ports:
      - "8100:8100"
      - "8501:8501"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./initial_data/company_credit_scores.csv:/docker-entrypoint-initdb.d/company_credit_scores.csv
    restart: always

volumes:
  pgdata:
